<?php

// $Id$

/**
 * Implements hook_permission().
 */
function properties_template_permission() {
  return array(
    'administer properties templates' => array(
      'title' => t('Administer templates'),
      'description' => t('Allows to create new, edit existing and delete templates.'),
    ),
    'add properties templates' => array(
      'title' => t('Add templates to content'),
      'description' => t('Allows to add an existing template to content.'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function properties_template_menu() {

  $items['admin/config/content/properties/templates'] = array(
    'title' => 'Templates',
    'page callback' => 'properties_template_admin_templates_list',
    'file' => 'properties_template.admin.inc',
    'access callback' => 'properties_admin_access',
    'access arguments' => array('templates'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 10,
  );

  $items['admin/config/content/properties/templates/list'] = array(
    'title' => 'List',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -30,
  );

  $items['admin/config/content/properties/templates/add'] = array(
    'title' => 'Add template',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('properties_template_admin_templates_form'),
    'file' => 'properties_template.admin.inc',
    'access callback' => 'properties_admin_access',
    'access arguments' => array('templates'),
    'type' => MENU_LOCAL_ACTION,
  );

  $items['admin/config/content/properties/templates/edit/%properties_template'] = array(
    'title' => 'Edit template',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('properties_template_admin_templates_form', 6),
    'file' => 'properties_template.admin.inc',
    'access callback' => 'properties_admin_access',
    'access arguments' => array('templates'),
    'type' => MENU_LOCAL_TASK,
    'weight' => -10,
  );

  $items['admin/config/content/properties/templates/delete/%properties_template'] = array(
    'title' => 'Delete template',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('properties_template_admin_templates_delete', 6),
    'file' => 'properties_template.admin.inc',
    'access callback' => 'properties_admin_access',
    'access arguments' => array('templates'),
    'type' => MENU_LOCAL_TASK,
  );

  return $items;
}


/**
 * Load a template based on the name.
 *
 * @param $name
 *   Template name.
 */
function properties_template_load($name) {
  if (empty($name)) {
    return FALSE;
  }
  $function_name = _properties_get_call('template', 'load');
  return $function_name($name);
}

/**
 * Load multiple templates based on their names.
 *
 * @param $names
 *   Array of template names.
 */
function properties_template_load_multiple($names = array()) {
  $function_name = _properties_get_call('template', 'load_multiple');
  return $function_name($names);
}

/**
 * Load a paged amount of templates.
 * @param $per_page
 *   Number of templates per page.
 */
function properties_template_load_paging($per_page, array $options = array()) {
  $function_name = _properties_get_call('template', 'load_paging');
  return $function_name($per_page, $options);
}

/**
 * Save a template object.
 *
 * @param $template
 *   Template object.
 */
function properties_template_save($template) {
  foreach ($template->categories as $delta => $category) {
    // New category, save it first.
    if (!empty($category->new)) {
      properties_category_save($category);
    }
    // Empty category, remove from array.
    if (empty($category->name)) {
      unset($template->categories[$delta]);
    }
  }
  $function_name = _properties_get_call('template', 'save');
  return $function_name($template);
}

/**
 * Delete a template.
 *
 * @param $template
 *   Template object.
 */
function properties_template_delete($template) {
  $function_name = _properties_get_call('template', 'delete');
  return $function_name($template);
}

/**
 * Implements hook_theme().
 */
function properties_template_theme() {
  return array(
    'properties_template_admin_templates_categories_form' => array(
      'render element' => 'element',
      'file' => 'properties_template.admin.inc',
    ),
  );
}